{
 "title": "SR policy monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "PolicyName",
    "query": "show tag values from \"Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-advertisement-verboses/sr-policy-last-advertisement-verbose\" with key=\"sr-policy-name\""
   }
  ]
 },
 "panels": [
  { "title": "Per Policy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "policy_id" },
  {
   "title": "Policy Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy",
     "query": "SELECT last(\"operational_up\") FROM \"Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy\" WHERE (\"policy_name\" =~ /^$PolicyName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Session  UP",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-liveness-detection-verboses/sr-policy-last-liveness-detection-verbose",
     "select": [
      [
       {
        "params": [
         "candidate_path/segment_list/liveness_detection_info/session_is_up"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "sr-policy-name", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  {
   "title": "Policy Delay (μs)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-aggregation-verboses/sr-policy-last-aggregation-verbose",
     "query": "SELECT last(\"candidate_path/metrics/average\") FROM \"Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-advertisement-verboses/sr-policy-last-advertisement-verbose\" WHERE (\"sr-policy-name\" =~ /^$PolicyName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Policy Color",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"color\") FROM \"Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy\" WHERE (\"policy_name\" =~ /^$PolicyName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Policy ID",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy",
     "query": "SELECT last(\"ls_ps/policy_id\") FROM \"Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy\" WHERE (\"policy_name\" =~ /^$PolicyName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "ls_ps/policy_id" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Operational Status",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$PolicyName-Oper-Status",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "/^$PolicyID$/" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy",
     "query": "SELECT (\"operational_up\") FROM \"Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy\" WHERE (\"policy_name\" =~ /^$PolicyName$/) AND $timeFilter ",
     "select": [
      [
       { "params": [ "operational_up" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "policy_name" ], "type": "field" },
       { "params": [ "name" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "id", "operator": "=~", "value": "/^$PolicyID$/" }
     ]
    }
   ]
  },
  {
   "title": "Latency (μs)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "μs" }
   ],
   "targets": [
    {
     "alias": "$PolicyName-Delay",
     "measurement": "Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-probes/sr-policy-last-probe",
     "query": "SELECT \"candidate_path/metrics/average\"/1000 FROM \"Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-advertisement-verboses/sr-policy-last-advertisement-verbose\" WHERE (\"sr-policy-name\" =~ /^$PolicyName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "candidate_path/metrics/average" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "sr-policy-name", "operator": "=~", "value": "/^$PolicyName$/" }
     ]
    }
   ]
  },
  { "title": "Policy Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Policies Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "id" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy",
     "query": "SELECT last(\"policy_name\"), \"color\", \"destination_address/ipv4\", \"operational_up\" FROM \"Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policies/policy\" WHERE $timeFilter GROUP BY \"id\"",
     "select": [
      [
       { "params": [ "policy_name" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "color" ], "type": "field" }
      ],
      [
       { "params": [ "destination_address/ipv4" ], "type": "field" }
      ],
      [
       { "params": [ "operational_up" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "UP Policy Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policy-summary",
     "select": [
      [
       { "params": [ "up_policy_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DOWN Policy Count",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "Cisco-IOS-XR-infra-xtc-agent-oper:xtc/policy-summary",
     "select": [
      [
       { "params": [ "down_policy_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SRTE Policy Latency",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_sr-policy-name]]",
     "groupBy": [
      { "params": [ "sr-policy-name" ], "type": "tag" }
     ],
     "measurement": "Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-probe-verboses/sr-policy-last-probe-verbose",
     "query": "SELECT \"candidate_path/metrics/average\" FROM \"Cisco-IOS-XR-perf-meas-oper:performance-measurement/nodes/node/sr-policies/sr-policy-delay/sr-policy-last-aggregation-verboses/sr-policy-last-aggregation-verbose\" WHERE $timeFilter GROUP BY \"sr-policy-name\"",
     "select": [
      [
       { "params": [ "candidate_path/metrics/average" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}